package com.hw.airport.sGUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author simon grange
 */
public class UpdatePassengersCheckedIn extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePassenger CheckIn - 
     * this is an extra form to report to the staff that the passengers have checked in
     */
    public UpdatePassengersCheckedIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Pno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(240, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Passenger Records Update", 0, 0, new java.awt.Font("Helvetica", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
   /*
        Provide the r g b values
       jLabel3.setText(new Color(0, 139, 139)) 
		   */
		   
        jLabel3.setText("Last Name");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(80, 120, 100, 22);

        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel4.setText("Baggage");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(450, 180, 60, 22);

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel5.setText("Passenger");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(450, 240, 60, 22);

        Submit.setText("Check In Status");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        
        /* 
         *   Panel buttons
         */
        
        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel6.setText("Check In Process Complete");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(80, 180, 60, 22);

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel7.setText("Fees Paid");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(80, 230, 143, 22);

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        
        jPanel3.add(Submit);
        Submit.setBounds(625, 303, 77, 39);
        
        jPanel3.add(Cancel);
        Cancel.setBounds(80, 303, 77, 39);

        jLabel8.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel8.setText("Passenger Booking Number");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(80, 60, 130, 22);

        Pno.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        Pno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnoActionPerformed(evt);
            }
        });
        jPanel3.add(Pno);
        Pno.setBounds(240, 50, 160, 32);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(540, 40, 91, 36);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checked In", "Checking In", "Not Checked In", "Cancelled", "Delayed", "Seeking Assistance" }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(240, 170, 180, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baggage Checked In", "Baggage Checking In", "Baggage Not Checked In", "Baggage Check In Cancelled", "Delayed", "Seeking Assistance"  }));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(540, 170, 180, 40);

        // <ay ot need additional fields (combo boxes) in stage 1
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checked In", "Checking In", "Not Checked In", "Cancelled", "Delayed", "Seeking Assistance"  }));
        jPanel3.add(jComboBox3);
        jComboBox3.setBounds(240, 230, 180, 40);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Progress", "Completed", "Computer Says No!", "Offer Upgrade", "Call Security", "Seek Assistance"  }));
        jPanel3.add(jComboBox4);
        jComboBox4.setBounds(540, 230, 180, 40);

        Name.setEditable(false);
        Name.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel3.add(Name);
        Name.setBounds(240, 120, 190, 32);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 80, 760, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
            Integer array[] = {Integer.parseInt(jComboBox1.getSelectedItem().toString()),Integer.parseInt(jComboBox2.getSelectedItem().toString()),Integer.parseInt(jComboBox3.getSelectedItem().toString()),Integer.parseInt(jComboBox4.getSelectedItem().toString())};

        try{

            FileReader fr = new FileReader("PassengerCheckedIn.txt");
                BufferedReader br = new BufferedReader(fr);

                String f = null;
                String parts[]=null;
                String data[]=new String[15];
                int i=0;
                while((f = br.readLine())!=null){
                    
                    parts = f.split(",");
                    if(parts[0].equals(Pno.getText())){
                        data[i] = Pno.getText()+","+Name.getText()+","+array[0]+","+array[1]+","+array[2]+","+array[3];
                        
                        i++;
                        
                    }else{
                        data[i] = f;
                        i++;
                    }
                    
                    
                }
                fr.close();
                br.close();
                
                FileWriter fout;

                fout = new FileWriter("PassengersCheckedIn.txt",false);

                
                for(int j=0; j<i;j++){
                    System.out.println(data[j]);
                    fout.write(data[j]);
                    fout.write(System.lineSeparator());
                }
                
                    
                
                fout.close();

                JOptionPane.showMessageDialog(null, "Updated Successfully");

                Manager obj = new Manager();
                obj.setVisible(true);
                this.setVisible(false);

        }catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_SubmitActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        Manager obj = new Manager();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void CnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if(Pno.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please Enter Passenger Booking Number");
        }else{

            try{

                FileReader fr = new FileReader("PassengersCheckedIn.txt");
                BufferedReader br = new BufferedReader(fr);

                String f = null;
                String parts[]=null;
                while((f = br.readLine())!=null){
                    parts = f.split(",");
                    if(parts[0].equals(Pno.getText()))
                    break;
                }
                fr.close();
                br.close();
                if(f==null){
                    JOptionPane.showMessageDialog(null, "No Check In Information Found!");
                }else{
                    Name.setText(parts[1]);
                    Pno.setEditable(false);
                    
                    Submit.setVisible(true);
                    
                    int i = Integer.parseInt(parts[2]);
                    jComboBox1.setSelectedIndex(i);
                    i = Integer.parseInt(parts[3]);
                    jComboBox2.setSelectedIndex(i);
                    i = Integer.parseInt(parts[4]);
                    jComboBox3.setSelectedIndex(i);
                    i = Integer.parseInt(parts[5]);
                    jComboBox4.setSelectedIndex(i);
                    

                }

            }catch(IOException ex1){

                JOptionPane.showMessageDialog(null, "No Check In Information Found!");
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePassengersCheckedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePassengersCheckedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePassengersCheckedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePassengersCheckedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePassengersCheckedIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField Pno;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Submit;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
